import {
  IconAppleFilled,
  IconBarbellFilled,
  IconBedFilled,
  IconBookFilled,
  IconBottleFilled,
  IconChartAreaFilled,
  IconCheck,
  IconChefHat,
  IconCrossFilled,
  IconGymnastics,
  IconHeadphonesFilled,
  IconLanguage,
  IconListCheck,
  IconPencil,
  IconPlus,
  IconPray,
  IconSchool,
  IconStretching,
  IconSunrise,
  IconSunset,
  IconTrash,
} from "@tabler/icons-react";

export const HabitIconMap = {
  workout: IconBarbellFilled,
  book: IconBookFilled,
  bed: IconBedFilled,
  pencil: IconPencil,
  list: IconListCheck,
  apple: IconAppleFilled,
  check: IconCheck,
  pray: IconPray,
  language: IconLanguage,
  headphones: IconHeadphonesFilled,
  stretching: IconStretching,
  gymnastics: IconGymnastics,
  cross: IconCrossFilled,
  sunrise: IconSunrise,
  sunset: IconSunset,
  school: IconSchool,
  bottle: IconBottleFilled,
  chefHat: IconChefHat,
  stats: IconChartAreaFilled,
  plus: IconPlus,
  trash: IconTrash,
};

export type HabitIconName = keyof typeof HabitIconMap;
