import {
  IconAppleFilled,
  IconArchive,
  IconBarbellFilled,
  IconBedFilled,
  IconBellRinging,
  IconBike,
  IconBookFilled,
  IconBookmark,
  IconBooks,
  IconBottleFilled,
  IconBox,
  IconBrain,
  IconBulb,
  IconCalendar,
  IconCalendarMonth,
  IconCalendarTime,
  IconCalendarWeek,
  IconCamera,
  IconChartAreaFilled,
  IconChartBar,
  IconChartLine,
  IconCheck,
  IconChecklist,
  IconChefHat,
  IconClock,
  IconClockPlay,
  IconCode,
  IconCoin,
  IconCrossFilled,
  IconDeviceMobile,
  IconDevicesMinus,
  IconEdit,
  IconFlag,
  IconFlame,
  IconFolder,
  IconFridge,
  IconGymnastics,
  IconHeadphonesFilled,
  IconHeart,
  IconHeartHandshake,
  IconHearts,
  IconHistory,
  IconLanguage,
  IconLeaf,
  IconList,
  IconListCheck,
  IconLungs,
  IconMail,
  IconMessages,
  IconMoodSmile,
  IconMoon,
  IconNotebook,
  IconPalette,
  IconPencil,
  IconPencilBolt,
  IconPigMoney,
  IconPill,
  IconPlant2,
  IconPlus,
  IconPray,
  IconQuestionMark,
  IconRecycle,
  IconRepeat,
  IconRun,
  IconSalad,
  IconScale,
  IconSchool,
  IconSearch,
  IconSettings,
  IconShare,
  IconStretching,
  IconSunrise,
  IconSunset,
  IconSwimming,
  IconTarget,
  IconTools,
  IconTrash,
  IconTrendingUp,
  IconTrophy,
  IconUserPlus,
  IconUsers,
  IconWalk,
  IconYoga,
} from "@tabler/icons-react";

export const HabitIconMap = {
  // Exercise & Physical Activity
  barbell: IconBarbellFilled,
  stretching: IconStretching,
  gymnastics: IconGymnastics,
  run: IconRun,
  swimming: IconSwimming,
  yoga: IconYoga,
  walk: IconWalk,
  bike: IconBike,

  // Nutrition & Health
  apple: IconAppleFilled,
  bottle: IconBottleFilled,
  chefHat: IconChefHat,
  salad: IconSalad,
  pill: IconPill,
  clock: IconClock,
  fridge: IconFridge,
  scale: IconScale,

  // Sleep & Rest
  bed: IconBedFilled,
  sunrise: IconSunrise,
  sunset: IconSunset,
  moon: IconMoon,

  // Mental Health & Wellness
  brain: IconBrain,
  heartHandshake: IconHeartHandshake,
  notebook: IconNotebook,
  lungs: IconLungs,
  moodSmile: IconMoodSmile,

  // Learning & Development
  book: IconBookFilled,
  language: IconLanguage,
  school: IconSchool,
  books: IconBooks,
  search: IconSearch,
  code: IconCode,
  pencil: IconPencil,
  bookmark: IconBookmark,
  repeat: IconRepeat,

  // Productivity
  listCheck: IconListCheck,
  checklist: IconChecklist,
  calendarTime: IconCalendarTime,
  target: IconTarget,
  clockPlay: IconClockPlay,
  bulb: IconBulb,
  folder: IconFolder,

  // Spiritual & Mindful
  pray: IconPray,
  cross: IconCrossFilled,
  heart: IconHeart,

  // Creative
  palette: IconPalette,
  headphones: IconHeadphonesFilled,
  pencilBolt: IconPencilBolt,
  camera: IconCamera,
  tools: IconTools,

  // Social & Relationships
  users: IconUsers,
  hearts: IconHearts,
  userPlus: IconUserPlus,
  messages: IconMessages,

  // Finance & Organization
  pigMoney: IconPigMoney,
  coin: IconCoin,
  trendingUp: IconTrendingUp,
  box: IconBox,

  // Digital Wellness
  devicesMinus: IconDevicesMinus,
  deviceMobile: IconDeviceMobile,
  mail: IconMail,

  // Environmental
  recycle: IconRecycle,
  plant: IconPlant2,
  leaf: IconLeaf,

  // Utility Icons
  chartArea: IconChartAreaFilled,
  plus: IconPlus,
  trash: IconTrash,
  edit: IconEdit,
  settings: IconSettings,
  calendar: IconCalendar,
  check: IconCheck,
  bellRinging: IconBellRinging,
  category: IconFolder,
  archive: IconArchive,
  share: IconShare,

  // Time-based
  morning: IconSunrise,
  evening: IconSunset,
  calendarWeek: IconCalendarWeek,
  calendarMonth: IconCalendarMonth,

  // Progress & Metrics
  chartBar: IconChartBar,
  flag: IconFlag,
  trophy: IconTrophy,
  flame: IconFlame,
  chartLine: IconChartLine,
  history: IconHistory,

  questionMark: IconQuestionMark,
  list: IconList,
};

export type HabitIconName = keyof typeof HabitIconMap;
